### ISSUE TITLE
Chinese dsi menu request

### ISSUE THREAD

**Issue by Darth-Koopa** [DS-Homebrew/TWiLightMenu#1034]
Issue:
![image](https://user-images.githubusercontent.com/45894930/81510620-15d81100-92e1-11ea-9b66-2f5355bb7071.png)

Currently if I select the language as Chinese, the dsi menu will show a mixture of Chinese characters as descriptions and a English background
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/45894930/81510651-6e0f1300-92e1-11ea-95f7-df20f513f012.png)
On the bottom screen, I'd like to change "Nintendo DSI Menu" in the background to "IQue DSI 菜单" as what is shown in a real idsi.
![image](https://user-images.githubusercontent.com/45894930/81510780-7b78cd00-92e2-11ea-907a-3707e4f7b7f2.png)
And on the top screen, change "No Photo." to "已拍摄的照片会显示在上屏幕。当主机中有多张相片时，每次开机显示的相片都将不同。"

**Comment by riverscn** [comment]
Some Chinese character is missing in game title display.

**Comment by Epicpkmn11** [comment]
> Some Chinese character is missing in game title display.

Hmm, which ones? I thought #1110 should have added all the ones that were used in retail games...

---

Also about the main issue here, I don't think any of that is translatable at all currently so it'd probably be good to make that fully translatable for all languages, or at least the ones Nintendo supported, rather than just Chinese. That'd probably be a good thing to do if/when we ever get around to making the DSi based themes not use GL2D as that could probably be done better then, I might try do that at some point, I just haven't felt like it as its such a bit change...

**Comment by riverscn** [comment]
> > Some Chinese character is missing in game title display.
> 
> Hmm, which ones? I thought #1110 should have added all the ones that were used in retail games...
> 
> Also about the main issue here, I don't think any of that is translatable at all currently so it'd probably be good to make that fully translatable for all languages, or at least the ones Nintendo supported, rather than just Chinese. That'd probably be a good thing to do if/when we ever get around to making the DSi based themes not use GL2D as that could probably be done better then, I might try do that at some point, I just haven't felt like it as its such a bit change...

Oh I see,  the characters are limited. So some of fan-translated titles are garbled. Glad to see an all-language font support if that is possible

**Comment by Epicpkmn11** [comment]
> Oh I see, the characters are limited. So some of fan-translated titles are garbled. Glad to see an all-language font support if that is possible

Yeah, the fonts are kept to just the needed characters since adding too many causes RAM issues in DS mode. Using [custom skins](https://github.com/DS-Homebrew/TWiLightMenu/wiki/how-to-create-DSi-3DS-skins) you can add custom fonts, so using [nftr-editor](https://pk11.us/nftr-editor) you can load an existing font and add characters to it, here's some instructions on how:

1. Load the NFTR file in [nftr-editor](https://pk11.us/nftr-editor)
1. Click `Add characters` and enter in all the characters you want to add
   - Any duplicates will be ignored so just enter anything you might want
1. Set the font you want and click `Generate from font`
   - TWiLight uses [nintendo_NTLG-DB](https://github.com/DS-Homebrew/TWiLightMenu/raw/master/manual/resources/assets/font/nintendo_NTLG-DB.ttf) with the colors #FF00FF (transparent), #929292, #434343, #000000
   - You should probably choose not to regenerate existing characters as that will replace special ones like the buttons (U+E000 - U+E06B), if you want to use a different font without losing those you can `Remove characters` all normal characters, then re-add them all and generate missing characters
1. Click `Save`, then repeat on the other font
1. Put the `large.nftr` and `small.nftr` files in `sd:/_nds/TWiLightMenu/dsimenu/themes/[skin]/font/[large|small].nftr`

Here's the normal TWiLight files and some with more (Japanese) Kanji a person on Discord made a bit ago:
- Normal: [large.nftr](https://github.com/DS-Homebrew/TWiLightMenu/raw/master/romsel_dsimenutheme/nitrofiles/graphics/font/large.nftr), [small.nftr](https://github.com/DS-Homebrew/TWiLightMenu/raw/master/romsel_dsimenutheme/nitrofiles/graphics/font/small.nftr)
- Some more Kanji: [large.nftr](https://cdn.discordapp.com/attachments/489307733074640926/755987500841041920/large.nftr), [small.nftr](https://cdn.discordapp.com/attachments/489307733074640926/755987638514614312/small.nftr)

Might be a good idea to have some premade themes with more complete CJK character sets as as long as your not using a flashcard it should be fine RAM wise... I'll try remember to do that sometime soon...

**Comment by riverscn** [comment]
> > Oh I see, the characters are limited. So some of fan-translated titles are garbled. Glad to see an all-language font support if that is possible
> 
> Yeah, the fonts are kept to just the needed characters since adding too many causes RAM issues in DS mode. Using [custom skins](https://github.com/DS-Homebrew/TWiLightMenu/wiki/how-to-create-DSi-3DS-skins) you can add custom fonts, so using [nftr-editor](https://pk11.us/nftr-editor) you can load an existing font and add characters to it, here's some instructions on how:
> 
> 1. Load the NFTR file in [nftr-editor](https://pk11.us/nftr-editor)
> 2. Click `Add characters` and enter in all the characters you want to add
>    
>    * Any duplicates will be ignored so just enter anything you might want
> 3. Set the font you want and click `Generate from font`
>    
>    * TWiLight uses [nintendo_NTLG-DB](https://github.com/DS-Homebrew/TWiLightMenu/raw/master/manual/resources/assets/font/nintendo_NTLG-DB.ttf) with the colors #FF00FF (transparent), #929292, #434343, #000000 and those are set in app, not in the NFTR so I recommend using those too unless you change it in the `theme.ini`
>    * You should probably choose not to regenerate existing characters as that will replace special ones like the buttons (U+E000 - U+E06B), if you want to use a different font without losing those you can `Remove characters` all normal characters, then re-add them all and generate missing characters
> 4. Click `Save`, then repeat on the other font
> 5. Put the `large.nftr` and `small.nftr` files in `sd:/_nds/TWiLightMenu/dsimenu/themes/[skin]/font/[large|small].nftr`
> 
> Here's the normal TWiLight files and some with more (Japanese) Kanji a person on Discord made a bit ago:
> 
> * Normal: [large.nftr](https://github.com/DS-Homebrew/TWiLightMenu/raw/master/romsel_dsimenutheme/nitrofiles/graphics/font/large.nftr), [small.nftr](https://github.com/DS-Homebrew/TWiLightMenu/raw/master/romsel_dsimenutheme/nitrofiles/graphics/font/small.nftr)
> * Some more Kanji: [large.nftr](https://cdn.discordapp.com/attachments/489307733074640926/755987500841041920/large.nftr), [small.nftr](https://cdn.discordapp.com/attachments/489307733074640926/755987638514614312/small.nftr)
> 
> Might be a good idea to have some premade themes with more complete CJK character sets as as long as your not using a flashcard it should be fine RAM wise... I'll try remember to do that sometime soon...
> 
> Edit: Oh also if its just a few then I could just add them to the main fonts too if you can send the names of some popular ones or so, I just don't want to go adding the full sets of common Kanji / Hànzì or Hangul as if I did it'd start running out of RAM on flashcards (not sure how many were added in those with more Kanji but I think that's just Japanese ones and those are already like 2x the size of the current ones)

Thank you very much! There is a full list of these games. I figured out which characters are used in these titles:


`麻將围棋打砖块黑白剧情汉化版魂花牌滴眼泪远古封印之炎混乱迷宫大字库死神火焰传承者力训练暗巫女与众的戒指测试星球%游戏合集熊猫运动场帕逻辑思维电子乐成模拟软件玩爱相随文本新世纪福音战士工具东京台赌绯红房间辣数独问魔物塔法卵七日亡目万能先生泡妞活夜晚把妹实篇修正天三国志重润上旋高手海最终下课后少年界树诸王圣杯个人中娃向前冲完美为你而整主题公园乌龙派出所简英语二漆导从今开始卡路里南仙境说代号基亚斯反叛鲁令旗任何地方都用家计狗吉拉布多腊肠犬伊苏言翠君夏色射佐贺超级阿嬷勇使命召唤争全现员侠盗车血唐街便利商店经营俄罗聚会豪华器烧录僵尸式复术鬼屋元气史莱姆菜单克骑和武脑系列秋山仁教授监兽演冒险岛冰决意标记刑事哈德簿曼顿安曲杀吻警俱部创典体造职业棒队森亨管理故斗恶怪被引们藏空娘幻非统守望优专北欧负罪千不看坦片师历答通厨老妈双忆口袋妖宝可梦巡护珍珠金心钻石银灵信长野议青救助时探光轨迹波精共鸣皇冠右回转柴解谜达爽找茬博馆弹头名侦柯来自过去奏消失错苍蓝轮舞田一交两位葵进发喷脉噗哟周噬杜莎阴谋四叶草门艺得更强圈套隐官邸洁狱朱蔓结堆积木堕甜蜜诱惑快感塞尔汽笛影沙漏剑读书恐怖学校谈略小太阳航翼激突破莲外丸入侵机飞诛降季节鼓以触摸敲落夺猎道奇好想告诉递培育恋己见兴采烈律妮作室炼富寻军曹革脊赛巧妙移巴特幕末选组乔水浒黄幽仿原宋吧弧源瞳唱他尼脱役满将從頭開語單詞訓練画跳初序章判图萌狼划必功夫忍餐危乡风瓦奥变杰鸡际丁園禁錮市傳說城废墟肖像刻月十架幸存懒拍休闲我是制豚押奋应援团拼雄掌排格码贝隆马凌丽明香补彩虹牧符厂兄弟滚无咆哮繁限边越棍协认壶洞走昆虫比参究极窗真约束穴晶编环声欢歌深渊逃由未樱兰男关因有迎裕扫除于笔继追逐汀蔷薇卢江户川步面迦秘霸击没洛兹沃挑腹背旬贼巨装备淘桃仇尘驱噩吟诗滑雪对吃豆疾晓纹灼娜姬她伙伴爆丝建诞村孩到夕别闪耀康幼圆雅族辛料霍渡猿玛嘉起科寂徒會浮疯狂农度病院惊益智同甲·旅瞬寺郎宿央验伽–西云漫直窃立绘竞配第兵舰加密推番改防诅咒医粉索紧急紫线鸟芒楼袭绿踪遇鱼鲸灯孔雀企鹅九尾狐邪聪胜内觉醒苦难茶莉异藤堂介蚂蚁角沢奈撤退!柔炸陆算习预览许愿昏屏補诺雾谎财报械遗产司叽这行也执刀准热躲避提升垂钓半滩轻松载驾驶蔚铲逆赖求检裁钢镇压爸羽铁臂童河镜牙伯蕾册贰陨雷缪友箱咏叹调笼林漠肚脐骰雨易在篮驯毁灭善速量锋赤黎缎带锻梭译`

**Comment by riverscn** [comment]
By the way, recent font in different language has different "font weight".  It is not very good looking.
![image](https://user-images.githubusercontent.com/555062/95411312-c877d280-0958-11eb-8d7c-ccf68291cf6a.png)
(The Janpanese Hanji looks a bit darker, and Chinese Hanji looks a bit lighter)

I think some uni-language font is better, such as [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/).

**Comment by chyyran** [comment]
@Epicpkmn11 I have (presumably) the Chinese NFTRs here if it's useful. 
[chinese nftr.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/5396444/chinese.nftr.zip)

**Comment by ClassicOldSong** [comment]
I've created an NFTR that contains almost all CJK characters. Problem is that it takes too much memory that it cannot start any game using flashcart firmware. Change to nds-bootstrap works pretty fine for me. Font weight is fixed by taking all Nintendo modified characters out from the original NTLG font and replaced with NotoSansCKJ.

[CJK_with_Nintendo_NTLG.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/5561320/CJK_with_Nintendo_NTLG.zip)

![image](https://user-images.githubusercontent.com/10512422/99573413-0d3f6080-2a11-11eb-9ed3-644f156f297c.png)

**Comment by Epicpkmn11** [comment]
> By the way, recent font in different language has different "font weight". It is not very good looking.
> ![image](https://user-images.githubusercontent.com/555062/95411312-c877d280-0958-11eb-8d7c-ccf68291cf6a.png)
> (The Janpanese Hanji looks a bit darker, and Chinese Hanji looks a bit lighter)
> 
> I think some uni-language font is better, such as [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/).

Oh, I forgot to get back to this. The font weight issue should be fixed in the latest version (probably since about v16.6.0, I forget exactly) as I made nintendo_NTLG-DB_001 be marked as a bold font when generating and told it to bold the fallback so they match much closer now.

For adding those characters to the font they add about 42KB to the large and 35KB to the small which I think should be fine, but it'll need to be tested and I don't know where my flashcard is atm so here's a build: [dsimenu.srldr.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/5611675/dsimenu.srldr.zip). That is still like a 20% increase though so it might be better left to external fonts... Maybe I should add a font setting to settings that applies to settings, the manual, and the dsi theme and then we could just have one file on the SD for them all instead of needing copies in all their NitroFS and it'd be easier to include more complete fonts for DSi/3DS while having a more cut down one on flashcards

**Comment by Epicpkmn11** [comment]
The "No photo." image will be translatable with #1401, however the background still won't be as that's a themable image.

**Comment by CaiMiao** [comment]
Sorry for digging but I made some super legible pixel fonts for Simp.Chinese with help of a random proprietary soft.

Regarding [wqybitmapsong-11px_twlcnjis](https://github.com/CaiMiao/DS-homebrew-font-backup/tree/master/twilight_menu/wqybitmapsong-11px_twlcnjis) font, I replaced all CJK characters in the official TWL CN font with the opensource `wqy bitmap song`  font, and character set is expanded to include all GB2312 + JIS CJK characters defined in both `.xlor` files.

**Comment by Epicpkmn11** [comment]
Looks nice, I did a PR (#1812) to switch to that since yeah that should save a couple MB in the 7z. I see you've got several others there too, I added a Fonts section to [twlmenu-extras](https://github.com/DS-Homebrew/twlmenu-extras) fyi so if you want you can PR them to there and they'll be accessible from the [skins site](https://skins.ds-homebrew.com/font/) and Universal-Updater.

In #1812 I named it 'WenQuanYi Bitmap Song' instead of 'Chinese (Simplified)' since using the same name would conflict where it wouldn't remove the old `large.nftr` so you'd have a mix.

**Comment by Epicpkmn11** [comment]
There's now an [iQue skin](https://skins.ds-homebrew.com/nintendo-dsi/default-white-ique) on the skins site so I think this issue is complete.

**Comment by Epicpkmn11** [comment]
You can easily change the no photo image by putting a PNG of the original in `sd:/_nds/TWiLightMenu/dsimenu/photos`
![no-photo](https://user-images.githubusercontent.com/41608708/156626869-d4597ba3-62bc-496a-be01-cd89588bb6a1.png)


 If you want the L/R text to say camera, can just copy that out of your screenshot too and replace the `Lshoulder.png`/`Rshoulder.png` files.
