### ISSUE TITLE
Startup is slow on large SD cards

### ISSUE THREAD

**Issue by chyyran** [DS-Homebrew/TWiLightMenu#1211]
Moved from #1196

**Comment by chyyran** [comment]
Hoping libslim in #1208 may improve this

**Comment by ObscureExtractor** [comment]
If anybody is still having this issue whether it be on any DS or any 3DS. Just simply close the system for a few seconds and open it back up. It works for me every time and hopefully someone found this helpful.

**Comment by Horonelius** [comment]
You can also just press the home button and then exit back to Twilight Menu.

**Comment by popy2k14** [comment]
If have this issue on booth of my DSi-XLs sometimes.
On boot, i get the DS Logo and "touch message".
After touching the screen went white and DS seems to stuck there.
Sometimes after a few seconds the menu appears.
If it's stucked, i just press "Power" short to reboot it and try it again.

I have tried the following to solve the issue:

- reformated SDcard with "SD formatter" ans reinstalled TWL++ -> same issue
- copied the contents to another brand new Sandisk Ultra Exreme Memory card -> same issue
- reformated new SDcard with "SD formatter" ans reinstalled TWL++ -> same issue

An hints how this issue can be solved?
Can we help with logs?

thx

**Comment by HAMBRUGNATCHERS** [comment]
This issue has a temporary fix. When you are stuck on the white screen, close your DS and reopen it. Make sure when you close it, the screen turns off. After opening it, wait 5-10 seconds. It should boot like normal.

**Comment by popy2k14** [comment]
Thx for the hint. Will try it.
Are there plans to fix this issue?
I can help because it's happening frequently. 
How can I get logs?

**Comment by HAMBRUGNATCHERS** [comment]
Afaik, there are no plans to fix it. I made a bug report, and it was closed within 24 hours claiming: The problem cannot be replicated. That’s what I’ve always done, and it seems to work everytime. What do you mean by logs?

**Comment by chyyran** [comment]
The issue has to do with the SD card driver and how libfat interacts with
it. The hope was libslim would help but it seems to make the problem worse
for some, and not much better for others. I have been busy but I hope to
make some more progress with libslim later this month, but it will not fix
the problem entirely, to do so we need to fix the SD card driver.

**Comment by popy2k14** [comment]
@HAMBRUGNATCHERS By Logs i mean, how can i gather logs from the "issue" to post it here? (Sorry, i am not so deep in TWM++). But when you said you ahve already reported it,and it was closed, maybe its wasted time.

@chyyran i am here to test if you hae something in the pipeline. In my case the issue is very often.

thx for all your efforts and keep up the good work.

**Comment by Whatnoww** [comment]
I can reproduce the issue on my DSi XL. Sometimes closing and opening won't get it to boot.

**Comment by NightScript370** [comment]
Fixed by recent versions. Closing...

**Comment by NightScript370** [comment]
Wait, oops. I got confused by the patch notes and thought it was fixed. Best someone actually tests if this is fixed or not.

**Comment by Rose22** [comment]
> Wait, oops. I got confused by the patch notes and thought it was fixed. Best someone actually tests if this is fixed or not.

it's not fixed, i am having this problem. too bad no one else replied until 2022 but better late than never i guess

**Comment by NightScript370** [comment]
Please tell me which environment you are using on TWiLight Menu++. It might not be just the SD card size.

**Comment by NightScript370** [comment]
Might be improved via a potential SDMMC lib switch in the works.
