### ISSUE TITLE
Last Run ROM disables widescreen after a ""soft reset""

### ISSUE THREAD

**Issue by FlameKat53** [DS-Homebrew/TWiLightMenu#847]
**Console configuration:** Regular-size New 3DS, Luma 3DS v10.0.1-dfd50d9d (a Nightly)
**TWiLight Menu++ Version:** I am using nightly 67352c1, but it's the same as v11.2.0
**TWiLight Menu++ Theme:** DSi Theme

### Expected behaviour
Game *should* "soft reset" and keep widescreen.

### Actual behaviour
Game "soft resets" and widescreen is disabled.

### Steps to reproduce

1. Open a game that uses widescreen, I used Dementium: The Ward
2. Wait for it to load up and then press L+R+START+SELECT
3. Screens will go pure black (no backlight) for a bit, then the game will reopen and it will be in "4:3"

**Comment by RocketRobz** [comment]
rtcom should fix this soon.

**Comment by Kaisaan** [comment]
This issue still occurs on version 12.2.0. Tested with Super Mario 64 DS (USA),

**Comment by FlameKat53** [comment]
Dementium: The Ward makes no soft reset on nds-bootstrap v0.30.0 and TWiLight Menu++ v12.2.0

**Comment by Kaisaan** [comment]
Regular softresetting (pressing L+R+Start+Select) in Super Mario 64 DS (USA) works properly now, widescreen stays the same. Though, force-softresetting (Holding L+R+Start+Select) disables widescreen now.
