### ISSUE TITLE
Option "Show hidden files" ignores sort order

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/TWiLightMenu#886]
**Your console configuration:**

O3DS

**TWiLight Menu++ Version:**

Always latest nightly

**TWiLight Menu++ Theme:**

3DS

### Expected behaviour

Hidden files, when shown, respect sort order.

### Actual behaviour

Hidden files are shown at the beginning.

### Steps to reproduce

1. Hide some files from random positions
2. Set sort method to ```alphabetical```
3. Enable option ```Show hidden files```

**Comment by NightYoshi370** [comment]
Does this happen with the nightly builds?

**Comment by eku** [comment]
@NightYoshi370 yes, it does.

**Comment by NightYoshi370** [comment]
Sorry, I confused my words. I meant to say release

**Comment by eku** [comment]
@NightYoshi370 yes, the error is also in release 11.2.

**Comment by Epicpkmn11** [comment]
This should be fixed in #888 since FAT attributes are now used instead of prepending a `.` to the file name

**Comment by eku** [comment]
@RocketRobz  Please reopen this issue, as 104f051 does not fix it. I just tried it.

**Comment by Epicpkmn11** [comment]
Are the files still named with `.`'s at the beginning? They won't be auto renamed, but unhiding and rehiding will rename them

**Comment by eku** [comment]
@Epicpkmn11 It would have been nice to implement a migration instead of burdening the user with this. For a few files this might still be reasonable. For many files this is no fun.

**Comment by NightYoshi370** [comment]
When you use a nightly, you accept that anything could change at any moment. Plus, it causes a lot more problems than solutions

**Comment by chyyran** [comment]
Migrating from .files to hidden attribute would cause more trouble than it's worth. It's much easier and safer to write a script to do that than build it into twilightmenu.

**Comment by NightYoshi370** [comment]
Also, of course if in alphabetical, hidden files comes first. Periods are the first character in the dictionary.

That's another reason why we switched to FAT attributes. Please switch all your directories to that instead. Closing...

**Comment by eku** [comment]
@chyyran wrote:
> It's much easier and safer to write a script to do that than build it into twilightmenu.

Access to the SD card is only possible via an FTP connection, at least for me. Which script language did you have in mind? GodMode9?
