### ISSUE TITLE
Setting "last played rom at start"  triggers TWLMenu++ logo

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/TWiLightMenu#908]
**Your console configuration:**  O3DS, Luma
**TWiLight Menu++ Version:** 92e34e01
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour

Setting ```last played rom at start``` should trigger this feature.

### Actual behaviour

Setting ```last played rom at start```  triggers TWLMenu++ Logo  screen at start up.

### Steps to reproduce

1. Go to settings 
2. Enable  ```last played rom at start```
3. Restart

**Comment by NightYoshi370** [comment]
I can reproduce this on latest release, but it was fixed in the latest nightly.
https://github.com/DS-Homebrew/TWiLightMenu/commit/9bd5e5a87a60e9c9429357d1718736d32a9cc11f

Closning

**Comment by eku** [comment]
@NightYoshi370 just updated to 9bd5e5a8 and the bug is not fixed!

**Comment by RocketRobz** [comment]
Is the correct commit number shown in TWLMenu++ Settings?

**Comment by eku** [comment]
@RocketRobz yes, it is.

**Comment by RocketRobz** [comment]
Well, the feature works fine for me, so I'll keep this closed.

Please come to the Discord server for future assistance.
